### PR TITLE
Update on polarization notebook

### PR DESCRIPTION
**Pull request by jaadt7**
I rearranged the notebook so that all the control parameters and imports are set from the very 1st cell and introduced a command that suppresses and un-needed figure. I also modified the google collab link to open from my repository when I was testing and you will have to change it back.

### CODE REVIEW

**Comment by mbradle** [comment]
Good.  Could you modify cell 3 to read:

xp, yp, xm, ym, x1, y1 = ([] for i in range(6))

**Comment by mbradle** [comment]
Also, I would suggest separating out the assignment of a's and alpha's from the imports.

**Comment by jaadt7** [comment]
I updated the notebook, should be available for your revision

**Comment by mbradle** [comment]
I've stolen a bunch of your changes in my own main branch.  You might want to review the new conflicts.

**Comment by jaadt7** [comment]
Add me as a co-author and we're even hehe. As for the new conflicts, they could be resolved if you simply approve the merge.

**Comment by mbradle** [comment]
I still prefer the set up to be at the beginning.  I've otherwise already stolen a lot of your suggestions, so I'm going to close this request.  Thanks for the input.

**Comment by jaadt7** [comment]
Glad I was able to help

**Pull request closed without merging**
